### ISSUE TITLE
Problems with getting A Resource Record back of active domains

### ISSUE THREAD

**Issue by 1234qwerasdfyxcv** [namecoin/ncdns#123]
Hey,

I have a problem with getting back the A Resource Record with IP address when I resolute active domains using dig in combination with ncdns. As example for the domain ebags.bit I get an answer like this:

```
; <<>> DiG 9.14.9 <<>> @localhost -p 1025 ebags.bit
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10160
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: ea3edb255373aaf0 (echoed)
;; QUESTION SECTION:
;ebags.bit.                     IN      A

;; Query time: 18 msec
;; SERVER: 127.0.0.1#1025(127.0.0.1)
;; WHEN: Sat Feb 01 14:13:11 Mitteleuropõische Zeit 2020
;; MSG SIZE  rcvd: 50
```

For domains like 'jamieweb.bit' or 'nf.bit' I get an A record answer back though.

Is that a bug or intentional?

Thank you for provididng ncdns.

Greetings

**Comment by JeremyRand** [comment]
The [value of `d/ebags`](https://namebrow.se/name/d/ebags/) is `{"email":"info2019@cassini.tv"}`, so no `A` records are present; ncdns is working as expected here.
