### ISSUE TITLE
BTCD does not contain BTCEC package

### ISSUE THREAD

**Issue by sergeysedoy97** [namecoin/ncdns#162]
```
#0 17.20 github.com/namecoin/ncdns/namecoin imports
#0 17.20        github.com/namecoin/btcd/rpcclient imports
#0 17.20        github.com/btcsuite/btcutil imports
#0 17.20        github.com/btcsuite/btcd/btcec: module github.com/btcsuite/btcd@latest found (v0.23.1), but does not contain package github.com/btcsuite/btcd/btcec
````

The latest version uses `btcec/v2`: https://pkg.go.dev/github.com/btcsuite/btcd/btcec/v2

Workaround: `go mod edit -require github.com/btcsuite/btcd@v0.22.1`

See https://github.com/btcsuite/btcd/issues/1887

**Comment by JeremyRand** [comment]
Hi!  Thanks for the bug report.  It looks like this is a side effect of the new btcd v0.23.1.  I suspect the right solution is to discontinue usage of Namecoin's fork of btcd, since v0.23.1 includes the final outstanding patch we were maintaining against upstream.

**Comment by JeremyRand** [comment]
Please let me know if this is still broken for you.

**Comment by Parikalp-Bhardwaj** [comment]
@JeremyRand 

Hi, i'm also facing the same issue 

github.com/btcsuite/btcd/btcec: module github.com/btcsuite/btcd@latest found (v0.24.2), but does not contain package github.com/btcsuite/btcd/btcec

**Comment by mjthecoder65** [comment]
I also experience the issue github.com/btcsuite/btcd/btcec: module github.com/btcsuite/btcd@latest found (v0.24.2), but does not contain package github.com/btcsuite/btcd/btcec

**Comment by JeremyRand** [comment]
> I also experience the issue github.com/btcsuite/btcd/btcec: module ***@***.*** found (v0.24.2), but does not contain package github.com/btcsuite/btcd/btcec

@mjthecoder65 Hi! Which commit hash of ncdns is showing the problems?

More generally, we're aware that ncdns is a pain to build right now. 
Robert's presentation at 38C3 included some info on how we're fixing this.
