### ISSUE TITLE
Port ncdns to OSX

### ISSUE THREAD

**Issue by dionyziz** [namecoin/ncdns#2]
We plan to use ncdns as part of a solution to enable namecoin-based hidden service name resolution for Tor. This support will require porting ncdns to OSX. What are your plans for that?

**Comment by hlandau** [comment]
`$ GOOS=darwin GOARCH=amd64 go build github.com/hlandau/ncdns`

Works fine for me. Is there some issue I'm not aware of?

**Comment by JeremyRand** [comment]
We distribute macOS binaries, so at this point I'd say it's clearly false that ncdns needs to be ported to macOS.  If there's a specific problem that we're unaware of, @dionyziz should file a new issue for it.
